### ISSUE TITLE
英文系统下，无法打开路径中带有东亚文字的图片，压缩包正常

### ISSUE THREAD

**Issue by AmeliaZ** [nessessary/SeeComic#2]
操作系统：Windows 10 20H2
系统语言：英文，设置区域为中国
问题：今天刚刚使用这款软件，发现路径或者文件名带汉字或日文的图片都提示“文件内容异常，不能加载”，压缩包则正常。

**Comment by nessessary** [comment]
我这没有英文系统， 用中文Win7切换到英文语言， 能正常打开。 请问是用最新版本碰到该问题的吗？较早的版本是有这个问题

**Comment by AmeliaZ** [comment]
哦，不好意思没注意最新版本是度盘下载的，用了Release里的版本。
